eval_type: 'eval1' 
models:
    mdl_pt_na:
        path: /home/dzubke/awni_speech/speech-lfs/examples/librispeech/models/ctc_models/2021-02-17/ph1/
        tag:
        filename: model_state_dict.pth
    mdl_pt_al:
        path: /home/dzubke/awni_speech/speech-lfs/examples/librispeech/models/ctc_models/2021-02-17/ph2/
        tag:
        filename: model_state_dict.pth
    mdl_fs_na:
        path: /home/dzubke/awni_speech/speech-lfs/examples/librispeech/models/ctc_models/2021-02-22/ph1/
        tag:
        filename: model_state_dict.pth
    mdl_fs_al:
        path: /home/dzubke/awni_speech/speech-lfs/examples/librispeech/models/ctc_models/2021-02-22/ph2/
        tag:
        filename: model_state_dict.pth
dataset_path: /mnt/disks/data_disk/data/speak_test_data/eval/eval3/spk-eval3-mispro_2021-02-25.json
output_path: /home/dzubke/awni_speech/speech-lfs/evaluate/eval1_aligner-eval3_2021-02-26.txt
lexicon_path: /home/dzubke/awni_speech/speech-lfs/data/lexicon/master-lexicon_2020-08-05.txt
n_top_beams: 1
